# Generated by Django 2.2.16 on 2021-11-22 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20211119_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Значение должно быть целым чиилом больше 0'), django.core.validators.MaxValueValidator(10, 'Значение должно быть целым числом меньше 11')], verbose_name='Оценка'),
        ),
    ]
